import { ApifyClient } from "apify-client";
import { loadEnv } from "../scripts/load-env.mjs";
import { query } from "../agent/lib/postgres";
import { uploadObject } from "../agent/lib/supabase-storage";

loadEnv();

const TRANSCRIPT_BUCKET = "ai-engineer-transcripts";
const DEFAULT_ACTOR_ID = "starvibe/youtube-video-transcript";
const DEFAULT_LIMIT = 2;
const DEFAULT_MIN_SECONDS = 600;
const DEFAULT_MAX_SECONDS = 1800;
const DEFAULT_CONCURRENCY = 4;

type Candidate = {
  video_id: string;
  title: string;
  url: string | null;
  duration_seconds: number;
  transcript_status: string;
  published_at: string | null;
};

type ActorSegment = {
  text?: unknown;
  start?: unknown;
  end?: unknown;
};

type ActorItem = {
  status?: unknown;
  message?: unknown;
  error?: unknown;
  language?: unknown;
  selected_language?: unknown;
  is_auto_generated?: unknown;
  transcript?: unknown;
  transcript_text?: unknown;
};

type IngestResult = {
  video_id: string;
  title: string;
  duration_seconds: number;
  status: "stored" | "missing" | "error" | "skipped";
  transcript_path?: string;
  transcript_char_count?: number;
  language?: string;
  apify_run_id?: string;
  error?: string;
};

function arg(name: string, fallback?: string): string | undefined {
  const idx = process.argv.indexOf(name);
  if (idx === -1) return fallback;
  return process.argv[idx + 1] ?? fallback;
}

function repeatedArg(name: string): string[] {
  const values: string[] = [];
  for (let i = 0; i < process.argv.length; i += 1) {
    if (process.argv[i] === name && process.argv[i + 1]) {
      values.push(process.argv[i + 1] as string);
    }
  }
  return values;
}

function asString(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0 ? value.trim() : null;
}

function youtubeUrl(video: Candidate): string {
  return video.url?.trim() || `https://www.youtube.com/watch?v=${video.video_id}`;
}

function transcriptPathFor(videoId: string): string {
  return `ai-dot-engineer/${videoId}.txt`;
}

function normalizeLanguage(item: ActorItem): string {
  const raw = asString(item.selected_language) ?? asString(item.language) ?? "en";
  const lowered = raw.toLowerCase();
  if (lowered.startsWith("en")) return "en";
  const iso = lowered.match(/^[a-z]{2}(?=[-_(]|$)/);
  return iso?.[0] ?? "en";
}

function textFromSegments(segments: unknown): string | null {
  if (!Array.isArray(segments)) return null;
  const lines = segments
    .map((segment) => asString((segment as ActorSegment).text))
    .filter((line): line is string => Boolean(line));
  if (lines.length === 0) return null;
  return lines.join("\n").trim();
}

function extractTranscript(item: ActorItem | undefined): {
  text: string | null;
  language: string;
  isAutoGenerated: boolean | null;
  actorStatus: string | null;
  actorMessage: string | null;
} {
  if (!item) {
    return { text: null, language: "en", isAutoGenerated: null, actorStatus: null, actorMessage: "empty_actor_dataset" };
  }
  const fromSegments = textFromSegments(item.transcript);
  const fromText = asString(item.transcript_text);
  return {
    text: fromSegments ?? fromText,
    language: normalizeLanguage(item),
    isAutoGenerated: typeof item.is_auto_generated === "boolean" ? item.is_auto_generated : null,
    actorStatus: asString(item.status),
    actorMessage: asString(item.message) ?? asString(item.error),
  };
}

async function listCandidates(options: {
  videoIds: string[];
  limit: number;
  minSeconds: number;
  maxSeconds: number;
}): Promise<Candidate[]> {
  if (options.videoIds.length > 0) {
    return query<Candidate>(
      `select video_id, title, url, duration_seconds, transcript_status, published_at
         from public.research_starter_videos
        where video_id = any($1::text[])
        order by published_at asc nulls last, video_id asc`,
      [options.videoIds],
    );
  }

  return query<Candidate>(
    `select video_id, title, url, duration_seconds, transcript_status, published_at
       from public.research_starter_videos
      where (transcript_status is distinct from 'stored'
             or transcript_text is null
             or length(btrim(coalesce(transcript_text, ''))) = 0)
        and duration_seconds between $1 and $2
      order by published_at asc nulls last, video_id asc
      limit $3`,
    [options.minSeconds, options.maxSeconds, options.limit],
  );
}

async function markStatus(
  videoId: string,
  status: "pending" | "stored" | "missing" | "error",
  extra: {
    error?: string | null;
    path?: string | null;
    language?: string | null;
    text?: string | null;
    charCount?: number | null;
    metadataPatch?: Record<string, unknown>;
  } = {},
): Promise<void> {
  await query(
    `update public.research_starter_videos
        set transcript_status = $2,
            transcript_error = $3,
            transcript_bucket = coalesce($4, transcript_bucket),
            transcript_path = coalesce($5, transcript_path),
            transcript_language = coalesce($6, transcript_language),
            transcript_char_count = coalesce($7, transcript_char_count),
            transcript_text = coalesce($8, transcript_text),
            transcript_fetched_at = case when $2 = 'stored' then timezone('utc', now()) else transcript_fetched_at end,
            metadata = coalesce(metadata, '{}'::jsonb) || coalesce($9::jsonb, '{}'::jsonb)
      where video_id = $1`,
    [
      videoId,
      status,
      extra.error ?? null,
      status === "stored" ? TRANSCRIPT_BUCKET : null,
      extra.path ?? null,
      extra.language ?? null,
      extra.charCount ?? null,
      extra.text ?? null,
      extra.metadataPatch ? JSON.stringify(extra.metadataPatch) : null,
    ],
  );
}

async function refreshQualification(videoId: string): Promise<void> {
  await query(`select research_private.refresh_pre_research_video_qualification($1)`, [videoId]);
}

async function ingestOne(client: ApifyClient, actorId: string, video: Candidate): Promise<IngestResult> {
  const base: IngestResult = {
    video_id: video.video_id,
    title: video.title,
    duration_seconds: video.duration_seconds,
    status: "error",
  };

  const claimed = await query<{ video_id: string }>(
    `update public.research_starter_videos
        set transcript_status = 'pending'
      where video_id = $1
        and transcript_status is distinct from 'stored'
      returning video_id`,
    [video.video_id],
  );
  if (claimed.length === 0) {
    return { ...base, status: "skipped", error: "already_stored" };
  }

  try {
    const callActor = (language?: string) =>
      client.actor(actorId).call(
        {
          youtube_url: youtubeUrl(video),
          include_transcript_text: true,
          ...(language ? { language } : {}),
        },
        { waitSecs: 300 },
      );

    let run = await callActor("en");
    let { items } = await client.dataset(run.defaultDatasetId).listItems();
    let extracted = extractTranscript(items[0] as ActorItem | undefined);
    const available = extracted.actorMessage?.match(/Available languages:\s*([a-z]{2}(?:-[A-Za-z]+)?)/i);
    if (!extracted.text && available?.[1]) {
      run = await callActor(available[1]);
      ({ items } = await client.dataset(run.defaultDatasetId).listItems());
      extracted = extractTranscript(items[0] as ActorItem | undefined);
    }
    const metadataPatch = {
      apify_transcript: {
        actor_id: actorId,
        run_id: run.id,
        dataset_id: run.defaultDatasetId,
        fetched_at: new Date().toISOString(),
        is_auto_generated: extracted.isAutoGenerated,
        actor_status: extracted.actorStatus,
      },
    };

    if (!extracted.text) {
      const missing = extracted.actorStatus === "error" || /not available|no transcript|limit_exceeded/i.test(extracted.actorMessage ?? "");
      const status = missing ? "missing" : "error";
      await markStatus(video.video_id, status, {
        error: extracted.actorMessage ?? "actor_returned_empty_transcript",
        metadataPatch,
      });
      return {
        ...base,
        status,
        apify_run_id: run.id,
        error: extracted.actorMessage ?? "actor_returned_empty_transcript",
      };
    }

    const path = transcriptPathFor(video.video_id);
    await uploadObject({
      bucket: TRANSCRIPT_BUCKET,
      path,
      body: extracted.text,
      contentType: "text/plain; charset=utf-8",
    });

    await markStatus(video.video_id, "stored", {
      path,
      language: extracted.language,
      text: extracted.text,
      charCount: extracted.text.length,
      metadataPatch,
    });
    await refreshQualification(video.video_id);

    return {
      ...base,
      status: "stored",
      transcript_path: path,
      transcript_char_count: extracted.text.length,
      language: extracted.language,
      apify_run_id: run.id,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await markStatus(video.video_id, "error", { error: message });
    return { ...base, status: "error", error: message };
  }
}

async function runPool<T>(items: T[], concurrency: number, worker: (item: T) => Promise<void>): Promise<void> {
  let next = 0;
  async function runWorker(): Promise<void> {
    while (true) {
      const index = next;
      next += 1;
      if (index >= items.length) return;
      await worker(items[index] as T);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, () => runWorker()));
}

const dryRun = process.argv.includes("--dry-run");
const runAll = process.argv.includes("--all");
const limit = Number(arg("--limit", runAll ? "5000" : String(DEFAULT_LIMIT)));
const minSeconds = Number(arg("--min-seconds", runAll ? "1" : String(DEFAULT_MIN_SECONDS)));
const maxSeconds = Number(arg("--max-seconds", runAll ? "3600" : String(DEFAULT_MAX_SECONDS)));
const concurrency = Number(arg("--concurrency", String(DEFAULT_CONCURRENCY)));
const videoIds = repeatedArg("--video-id");
const actorId = process.env.APIFY_TRANSCRIPT_ACTOR_ID?.trim() || DEFAULT_ACTOR_ID;
const token = process.env.APIFY_API_KEY?.trim();

if (!token) {
  throw new Error("APIFY_API_KEY is not set in .env");
}

const candidates = await listCandidates({
  videoIds,
  limit: Number.isFinite(limit) ? limit : DEFAULT_LIMIT,
  minSeconds: Number.isFinite(minSeconds) ? minSeconds : DEFAULT_MIN_SECONDS,
  maxSeconds: Number.isFinite(maxSeconds) ? maxSeconds : DEFAULT_MAX_SECONDS,
});

if (dryRun) {
  console.log(
    JSON.stringify(
      {
        dry_run: true,
        actor_id: actorId,
        count: candidates.length,
        min_seconds: minSeconds,
        max_seconds: maxSeconds,
        candidates: candidates.map((row) => ({
          video_id: row.video_id,
          title: row.title,
          duration_seconds: row.duration_seconds,
          transcript_status: row.transcript_status,
        })),
      },
      null,
      2,
    ),
  );
  process.exit(0);
}

const client = new ApifyClient({ token });
const results: IngestResult[] = [];
let finished = 0;
const startedAt = Date.now();
const workerCount = Number.isFinite(concurrency) && concurrency > 0 ? concurrency : DEFAULT_CONCURRENCY;

console.log(
  JSON.stringify({
    event: "start",
    actor_id: actorId,
    requested: candidates.length,
    min_seconds: minSeconds,
    max_seconds: maxSeconds,
    concurrency: workerCount,
  }),
);

await runPool(candidates, workerCount, async (video) => {
  const result = await ingestOne(client, actorId, video);
  results.push(result);
  finished += 1;
  const elapsedSec = Math.round((Date.now() - startedAt) / 1000);
  console.log(
    JSON.stringify({
      event: "progress",
      done: finished,
      total: candidates.length,
      elapsed_sec: elapsedSec,
      video_id: result.video_id,
      status: result.status,
      transcript_path: result.transcript_path ?? null,
      transcript_char_count: result.transcript_char_count ?? null,
      error: result.error ?? null,
    }),
  );
});

const summary = {
  event: "done",
  actor_id: actorId,
  requested: candidates.length,
  stored: results.filter((row) => row.status === "stored").length,
  missing: results.filter((row) => row.status === "missing").length,
  error: results.filter((row) => row.status === "error").length,
  skipped: results.filter((row) => row.status === "skipped").length,
  elapsed_sec: Math.round((Date.now() - startedAt) / 1000),
  results,
};

console.log(JSON.stringify(summary, null, 2));

if (results.some((row) => row.status === "error") && results.every((row) => row.status !== "stored")) {
  process.exit(1);
}
